<?php

namespace RecommandationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovieactorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieactorsRepository extends EntityRepository
{
}
