<?php

namespace RecommandationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MoviecolorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoviecolorsRepository extends EntityRepository
{
}
