<?php

namespace RecommandationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovielanguagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovielanguagesRepository extends EntityRepository
{
}
