<?php

namespace RecommandationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * YearsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearsRepository extends EntityRepository
{
}
