recommandation:
    resource: "@RecommandationBundle/Resources/config/routing.yml"
    prefix:   /

transversale:
    resource: "@TransversaleBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
